apiVersion: batch/v1
kind: CronJob
metadata:
  name: dunham-cron
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels: 
            name: dunham-cron
        spec:
          containers:
            - name: dunham
              image: docker.io/kwyn/dunham:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: dunham-dot-env
                mountPath: "/home/pptruser/workspace/secrets/"
                readOnly: true
              - name: {{ .name }}
                mountPath: "/home/pptruser/workspace/configmaps/"
          restartPolicy: Never
          volumes:
          - name: dunham-dot-env
            secret:
              secretName: dunham.env
          - name: {{ .name }}
            configMap:
              name: {{ .name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: 
    name: dunham-cron
  name: {{ .name }}
data:
  sites.json: |
    {{ .siteList }}
  dates.json: |
    {{ .dates }}

