apiVersion: batch/v1
kind: CronJob
metadata:
  name: feb-19th-job 
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels: 
            name: feb-19th-job 
        spec:
          containers:
            - name: dunham
              image: docker.io/kwyn/dunham:latest
              imagePullPolicy: IfNotPresent
              env:
              - name: NODE_ENV
                value: "production"
              volumeMounts:
              - name: dunham-dot-env
                mountPath: "/home/pptruser/workspace/secrets/"
                readOnly: true
              - name: feb-19th-config 
                mountPath: "/home/pptruser/workspace/configmaps/"
          restartPolicy: Never
          volumes:
          - name: dunham-dot-env
            secret:
              secretName: dunham.env
          - name: feb-19th-config 
            configMap:
              name: feb-19th-config 
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: 
    name: feb-19th-job 
  name: feb-19th-config 
data:
  sites.json: |
    [
      "Upper Pines",
      "Lower Pines",
      "North Pines"
    ]
  dates.json: |
    {
      "start": "02/19/2022",
      "end": "05/20/2022"
    }

