apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dunham.env
  namespace: dunham-prod
spec:
  encryptedData:
    .env: AgCxgEnONf4Dsk5XGuhMqmqpLVaFvUgiP6QliHANQmX+Ssthit1CAs3jknNBUbeyOdv5cur0IUs9BY1n9C1VR1M/5pUm4wwiFDu5MAQ6uazoKMgTbKG1d7pTA+drElcoYChuIEvNkb7bR9TnILHn5PcC+hqSRyqnizFRH5PkkbtePnAq7LuZbbI6rdeh2M3Rq2DRzv8VnwjKkjIU+H3N0g1nphQOUPbXPZEXauVOD87dUvVj4Tq9DF5ND1d3h8G8tYIhBvrZw4vPolxJAFdp2C0pbzy9ORhGe3HbIBW/eQ/AbrJHnSmGNKIr448kOFE84UWx1yIo3k2UO0lphey8hL9FdWv+3WHnplE8diXpWuI2SS7uIhfgiBSroDJZLfxz4lVRlZeRjJ98OgQkP2HdH7t6vluM3+UdPfdFznJsAa0zTFTUv8Ps/ctLdZcv5uhcaFhsfQLpJHasDnM8lZXWftSe9plJ5gxgk2v/w54petLCmVxnSXGYGXl52e2lmNX/3QSR4H7NdMQSHCTICe+LWBDE6waEwMYBLbC4buV57yJK66OZvS6RsT+Gy9cunE7Y2tKMerHouXmv6m/03RXfowEb169m6BpLDQIOVYMLmLM2mRfB+KzhpHFFWcvKGdvIRp3FBCeas3gaoPkuDzK2kNuJhVxk/4R481VxGDAmR6F0X5xc/tfbOEQh/Ipy6mJpl0QGw0EEoYqUJ++oUbRJPmzVRY1ZIj+pveNYpwbGSHx7J/rLUg1Jy/cWpUMuLUZwo3kjDqho54dxRmL8QIzwMYwwdTCB/cekoOhEpe/OFqJQNUctDIIkM2I1keCjArWk4VgIVTxUrw4jCvZjVCIbu8hyBGhyqFm0SVOcXQCnKuqceryNxcDjFAbUXTbymncVXNiBjXd7ByCjMH6x52zdC0+RFBC6oUHuBszR5c7fFcSinBavO2G6l+z1a8W+/w0vkMTIShTKVcNbPPvdNY2VQwkYmzccS8/GSlLBRRvxcegaC332oz/MFUdc02HtcSRjox5c3h42QxBpLpwLfQlA17xBIT6QrssMXQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dunham.env
      namespace: dunham-prod

