apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dunham.env
  namespace: dunham-dev
spec:
  encryptedData:
    .env: AgASm7nKbHUKMmR0yrX72yEWPudQ8Z466eqmk3KbHg83UsJQIpH6izlJkwYMsCHxOjS1pmPd4P1+jJ045KjdZIFxzAMyV+GB0tRmBhaPP55PeSxQFvO3u37l8++a5rmdjBIHNI7oq9Ka71/znC/HX5hzGBpJi/1k4VoihgMpGjas1QbKVbCJMAigVSuEVaWdWJrO7Vwl9atfJpDZeXvh4p86OoPmwk5RFQZiNO6DydLrIfLNCJ5qvwWgw8oJo0ZkF1Vg1xz2NebJsFM6CXwDq2HvzGmA8UVZUoLGABT5D11Met2ZayrcHjrHQRv0Dxoul2id1Gx+4k2uhLdNPiC/+8GeT7WyBw1rwGZZ6+l+I5mE8VGN2RTGY4yBH6/rB1jVSXBUj0W8tujpbqDe3wD9S9WuaRWSlel1sgpUZ4VXgJ34neqarR143r8vppvZo9A45VXjIKBXOpTlpVTxGtqz8vlDbrikz3OrwhD1slU4mcBKpo4+CWidbLgMPX8d+VoFbY7+TRRyqb+pvleNo/EuoEGLLKL5rykMQ3wA513DN83c2nGnuJLYEM7ztvoMmr0fFUiZMDvSugW4++vkzOtmmFWJYxBLYNVYcCQ/UidzRPk7sySub761dZYVnqmEBwp+d0obTC8+ckg0x5ACjFdZq7DEhP2ZeQOT2AYA9758lfZrvc79UPrduxVTy1Xf/0P5h8ehzW8gedWpgsB7wneqstkvWfANgu5OxXS1fAwNw9k6ENMvu+XpwNFIAfdU2xNT08dO+iQHP3E5dZYshvuGQAdpoNgFFhkWeuDhk1ElGR/lHREAeXqcvfjvPh33fFZYWLqkMYLiSjV2hvNkA6CWS1m9BG7ZOqkgIdqbs472syyf2XpCe4NSBhxfWmvF5HUVq5D6eFi1AJzsDA+I/5FfB+Z/6XRY7nqIGL2BuT0DfGix8A62wfL6poXXEvrY46D9DyHbLaI1Bmqf6cMAV6BPGlq3FJDLArJZqpx5VJmolP7D/501cJ2cPexN922PVJxLwjr/CRYsnW5O
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dunham.env
      namespace: dunham-dev

