name: deploy

# TODO: Check that code or config files actually changed before running pipeline

on:
  push:
    branches: ["*-deploy"]

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest                       
    steps:
    - 
      name: Cancel Previous Runs               
      uses: styfle/cancel-workflow-action@0.4.1
      with:                                    
        access_token: ${{ github.token }}
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # Fetch previous commit for file diff
    - 
      name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v12.2
    - 
      name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: "arm64"
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        config-inline: |
          [worker.oci]
            max-parallelism = 4
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kwyn
        password: ${{ secrets.DOCKERHUB_PW }}
    -
      name: build Dockerfiles/dunham.dockerfile
      run: |
        docker build --platform linux/arm64,linux/amd64 --push --file ./Dockerfiles/dunham.dockerfile --tag docker.io/kwyn/dunham:$GITHUB_SHA .
    -
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.GALACTIC_CONFIG }}
    - 
      name: Deploy to Kubernetes cluster                                                                            
      uses: Azure/k8s-deploy@v1.5
      with:                                                                                                         
        namespace: dunham-dev
        manifests: |
          deploy/sealed-env-dev.yaml
          deploy/cronjob.yaml
        images: |
          'docker.io/kwyn/dunham:${{ github.sha }}'
        kubectl-version: 'latest'