name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch previous commit for file diff
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12.2
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 4
      -
        name: build puppeteer
        if: contains(steps.changed-files.outputs.all_changed_files, 'Dockerfiles/puppeteer.dockerfile')
        env:
          PW: ${{ secrets.DOCKERHUB_PW}}
        run: |
          docker login --username kwyn --password "$PW"
          docker build -f ./Dockerfiles/puppeteer.dockerfile -t docker.io/kwyn/puppeteer:$GITHUB_SHA  -t docker.io/kwyn/puppeteer:latest .
          docker push docker.io/kwyn/puppeteer
      -
        name: build dunham
        if: contains(steps.changed-files.outputs.all_changed_files, 'Dockerfiles/puppeteer.dockerfile') || contains(steps.changed-files.outputs.all_changed_files, 'Dockerfiles/dunham.dockerfile')
        env:
          PW: ${{ secrets.DOCKERHUB_PW}}
        run: |
          docker login --username kwyn --password "$PW"
          docker build -f ./Dockerfiles/dunham.dockerfile -t docker.io/kwyn/dunham:$GITHUB_SHA .
          docker push docker.io/kwyn/dunham
