name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch previous commit for file diff
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12.2
      - 
        name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: "arm64"
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 4
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kwyn
          password: ${{ secrets.DOCKERHUB_PW }}
      -
        name: build Dockerfiles/puppeteer.dockerfile
        if: |
          (contains(steps.changed-files.outputs.all_changed_files, 'Dockerfiles/puppeteer.dockerfile') || 
          contains(steps.changed-files.outputs.all_changed_files, '.github/workflows/image_builds.yml'))
        run: |
          docker build --platform linux/arm64,linux/amd64 --push --file ./Dockerfiles/puppeteer.dockerfile --tag docker.io/kwyn/puppeteer:$GITHUB_SHA  --tag docker.io/kwyn/puppeteer:latest .
